--- 
text_extensions: 
- css
- erb
- haml
- htm
- html
- js
- less
- markdown
- md
- php
- rb
- sass
- txt
- xhtml
- xml
- coffee
output_dir: output
index_filenames: 
- index.html
enable_output_diff: false
base_url: http://localhost:3000
title: Website Title
author_name: Your Name
author_uri: Your Link
data_sources: 
- type: filesystem_unified
  items_root: /
  layouts_root: /
